version: "3"

services:

 # Proxies requests to the different containers so we can use real-ish hostnames while developing
  # nginx-proxy:
  #   build:
  #     context: ./docker/nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - application

  # client:
  #   image: node:8.6
  #   working_dir: /app
  #   entrypoint: ./docker-entrypoint.sh
  #   ports:
  #     - "7000:7000"
  #     - "443:443"
  #   networks:
  #     - application
  #   environment:
  #     NODE_ENV: "development"
  #     VIRTUAL_HOST: "*timer.test"
  #     VIRTUAL_PORT: 7000
  #   volumes:
  #     - ./apps/client:/app

  phoenix:
    build:
      context: ./docker/phoenix
    entrypoint: /app/entrypoint.sh
    ports:
      - "4000:4000"
    networks:
      - application
    volumes:
      - ./apps/api:/app
    working_dir: /app

  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: timer
    ports:
      - "6432:5432"
    networks:
      - application

  db-test:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: timer-test
    ports:
      - "7432:5432"
    networks:
      - application

networks:
  application:
